### PR TITLE
Modal for Instructions

### PR DESCRIPTION
**Pull request by veev**
This is a first attempt at a reasonable lift to make the graph instructions something people have to read before interacting with the graph. This addresses Issue #131. @lxu213 can you take a look and let me know what you think? If you like it, I can implement for the Chart and Graph views.

### CODE REVIEW

**Comment by lxu213** [comment]
@veev this looks pretty good! 

What if the `INSTRUCTIONS` was also clickable? Right now, it feels like it blends in with the side bar too much. I wonder how it'd look if it were the same "selectable" color blue as the plus sign?

**Comment by lxu213** [comment]
I like how the box zooms in and out of the plus sign

**Comment by veev** [comment]
> @veev this looks pretty good!
> 
> What if the `INSTRUCTIONS` was also clickable? Right now, it feels like it blends in with the side bar too much. I wonder how it'd look if it were the same "selectable" color blue as the plus sign?

@lxu213 I like this idea and can definitely try it out!

**Comment by veev** [comment]
image
Here's what it looks like. What do you think?

**Comment by lxu213** [comment]
I like it!

**Comment by veev** [comment]
ok cool, then I will start implementing this for the other views too.

**Comment by veev** [comment]
@lxu213 I added the modals to the other views. take a look when you get a chance. Not sure we need to merge this until we get copy updates from Elizabeth, but your call.

**Pull request merged**
